=== DuaDepTrai/Aptech_XML-JSON/src/Ex_241016/Ex2/books.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified"
            attributeFormDefault="unqualified">

    <xs:simpleType name="dateType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{4}-\d{2}-\d{2}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="books">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book"  maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="author" type="xs:string"/>
                            <xs:element name="genre">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Fiction"/>
                                        <xs:enumeration value="Non-fiction"/>
                                        <xs:enumeration value="Mystery"/>
                                        <xs:enumeration value="Fantasy"/>
                                        <xs:enumeration value="Sci-fi"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="price">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:minInclusive value="0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="publicationDate" type="dateType"/>
                            <xs:element name="coverImage">
                                <xs:simpleType>
                                    <xs:restriction base="xs:anyURI"/>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="description" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:positiveInteger"/>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== DuaDepTrai/Aptech_XML-JSON/src/Ex_241016/Ex2/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="books.xsl" type="text/xsl"?>

<books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="books.xsd">
    <book id="1">
        <title>The Great Gatsby</title>
        <author>F. Scott Fitzgerald</author>
        <genre>Fiction</genre>
        <price>15.99</price>
        <publicationDate>1925-04-10</publicationDate>
        <coverImage>images/gatsby.jpg</coverImage>
        <description>Một câu chuyện về tình yêu và bi kịch trong thập niên 1920.</description>
    </book>
    <book id="2">
        <title>The Hobbit</title>
        <author>J.R.R. Tolkien</author>
        <genre>Fantasy</genre>
        <price>25.50</price>
        <publicationDate>1937-09-21</publicationDate>
        <coverImage>images/hobbit.jpg</coverImage>
        <description>This is a fascinating book that takes readers on an unforgettable journey through time, space, and imagination, exploring themes of love, loss, and the human spirit in extraordinary ways.
        </description>
    </book>
</books>
