=== DuaDepTrai/Aptech_XML-JSON/src/Ex_241016/Ex3/movies.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified"
            attributeFormDefault="unqualified">

    <xs:element name="movies">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="movie"  maxOccurs="unbounded">

                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="genre">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Action"/>
                                        <xs:enumeration value="Sci-fi"/>
                                        <xs:enumeration value="Drama"/>
                                        <xs:enumeration value="Crime"/>
                                        <xs:enumeration value="Comedy"/>
                                        <xs:enumeration value="Romance"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="director" type="xs:string"/>
                            <xs:element name="releaseDate">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\d{4}-\d{2}-\d{2}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="rating">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:minInclusive value="1"/>
                                        <xs:maxInclusive value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="duration">
                                <xs:simpleType>
                                    <xs:restriction base="xs:positiveInteger"/>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="poster">
                                <xs:simpleType>
                                    <xs:restriction base="xs:anyURI"/>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="description" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:positiveInteger"/>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>        
    </xs:element>
</xs:schema>

=== DuaDepTrai/Aptech_XML-JSON/src/Ex_241016/Ex3/movies.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="movies.xsl" type="text/xsl"?>

<movies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="movies.xsd"> 
    <movie id="1">
        <title>Inception</title>
        <genre>Sci-fi</genre>
        <director>Christopher Nolan</director>
        <releaseDate>2010-07-16</releaseDate>
        <rating>9</rating>
        <duration>148</duration>
        <poster>https://example.com/poster1.jpg</poster>
        <description>A thief who steals corporate secrets through dream-sharing technology is given a chance to erase his criminal history by implanting an idea into a target's subconscious.</description>
    </movie>
    <movie id="2">
        <title>The Godfather</title>
        <genre>Crime</genre>
        <director>Francis Ford Coppola</director>
        <releaseDate>1972-03-24</releaseDate>
        <rating>9.2</rating>
        <duration>175</duration>
        <poster>https://example.com/poster2.jpg</poster>
        <description>The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.</description>
    </movie>
</movies>
